apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
       - name: helloworld
         image: jfrog-cr.10-35-151-40.nip.io/docker-local/helloworld:latest
         ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080
  selector:
    app: helloworld
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
spec:
  ingressClassName: nginx1
  rules:
   - host: helloworld.10-35-151-199.nip.io
     http:
       paths:
       - pathType: Prefix
         path: "/"
         backend:
           service:
             name: helloworld
             port:
               number: 80
